[connection]
ipv6.ipv6-privacy=2
ipv4.dhcp-timeout=30
ipv4.dhcp-client=internal
connection.autoconnect-retries=5
ethernet.mtu=1492

[device-wifi]
wifi.powersave=1
wifi.scan-rand-mac-address=no

[main]
no-auto-default=*
ignore-carrier=wlan0

[connectivity]
uri=https://connectivity.jinaos.com/check
interval=300
response=ok
enabled=true