/var/log/messages {
	rotate 5
	size 10M
	compress
	missingok
	notifempty
}

/var/log/jpm.log {
	rotate 3
	size 10M
	compress
	missingok
	notifempty
	postrotate
		/usr/bin/jpm cache-clean > /dev/null 2>&1
		endscript
}

/var/log/weston.log {
	rotate 2
	size 10M
	compress
	missingok
	notifempty
}