net.ipv4.tcp_window_scaling=1
net.ipv4.tcp_rmem=4096 87380 6291456
net.ipv4.tcp_wmem=4096 16384 4194304
net.core.rmem_default=87380
net.core.wmem_default=16384
net.core.rmem_max=6291456
net.core.wmem_max=4194304
net.ipv4.tcp_stack=1
net.ipv4.tcp_dsack=1
net.ipv4.tcp_fack=1
net.ipv4.tcp_syncookies=1
net.ipv4.tcp_timestamps=1
net.ipv4.tcp_retries2=15
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_no_metrics_save=1
net.ipv4.tcp_moderate_rcvbuf=1
net.ipv4.tcp_rfc1337=1
net.ipv4.tcp_mtu_probing=1