msm
msm_drm
panel_ili9881c
goodix_ts
snd_soc_msm89xx
snd_soc_wcd9335
qca_cld3
cnss_utils
qrtr
pm8941_pwrkey
qcom_spmi_temp_alarm
qcom_spmi_pmic_arb
bq27xx_battery
usb_f_diag
usb_f_qdss
ci_hdrc
dwc3
dwc3_msm
spi_qsd
i2c_qup
mt76x0u
rrtl8189fs
wlan
btusb
btrtl