#!/bin/sh

IPTABLES=/sbin/iptables
IP6TABLES=/sbin/ip6tables
RULES_V4=/etc/iptables/rules
RULES_V6=/etc/iptables/rules.v6

case "$1" in
  start)
	echo "Loading iptables rules..."
	if [ -f $RULES_V4 ]; then
		$IPTABLES-restore < $RULES_V4
	fi
	if [ -f $RULES_V6 ]; then
		$IP6TABLES-restore < $RULES_V6
	fi
	;;
  stop)
	echo "Flushing iptables rules..."
	$IPTABLES -F
	$IPTABLES -X
	$IPTABLES -t nat -F
	$IPTABLES -t mangle -F
	$IPTABLES -P INPUT ACCEPT
	$IPTABLES -P FORWARD ACCEPT
	$IPTABLES -P OUTPUT ACCEPT
	$IP6TABLES -F
	$IP6TABLES -X
	$IP6TABLES -t nat -F
	$IP6TABLES -t mangle -F
	$IP6TABLES -P INPUT ACCEPT
	$IP6TABLES -P FORWARD ACCEPT
	$IP6TABLES -P OUTPUT ACCEPT
	;;
  restart)
	$0 stop
	$0 start
	;;
  status)
	echo "Current iptables rules:"
	$IPTABLES -L -n -v
	$IP6TABLES -L -n -v
	;;
  *)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
	;;
esac

exit 0